# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
