class AddDomperereToWord < ActiveRecord::Migration[6.0]
  def up
    add_column :words, :uitdrukking, :integer, default: 1
    Word.reset_column_information
    source = Source.create(name: 'Dòmpereré pa palabra pèrdí i nobo', comment: 'Lista di palabra i ekspreshon
        pa tayer di skibimentu
        Dòmpereré pa palabra pèrdí i nobo

        2017-2018

        E tim di e proyekto Dòmpereré ta gradisí tur ku a partisipá na e kampaña Dòmpereré pa palabra pèrdí i nobo na sèptèmber 2017 i ku gran entusiasmo a entregá palabra i ekspreshon bieu i nobo di nos dushi lenga papiamentu. Despues di un selekshon minusioso e resultado di esaki ta e glosario ku bo tin bo dilanti.

        Tambe nos ta gradisí tur medio di komunikashon, persona i instansia, spesialmente Landhuis Bloemhof, ku a sostené i apoyá e kampaña i tur otro ku di òf un otro forma a kontribuí ku diskushon i komentario den medionan sosial i/òf di otro manera.

        Spesialmente nos ta yama danki na e komishon di sabio, kende ku dedikashon a reuní oranan largu, pa deliberá riba kada palabra i ekspreshon ku e partisipantenan na e kampaña a entregá. E komishon akí tabata konsistí di: Thelma Anthonia, Lucille Berry-Haseth, Diane Henriquez, Philip Rademaker i Ini Statia. Por último Tittel Boomgaart a djòin e komishon komo un konosedó hóben di papiamentu, spesialmente di e mundu i yargon hóben.

        Un danki masha grandi ta bai na Lucille Berry-Haseth, kende a redaktá i perfekshoná deskripshon di kada nifikashon ku un diligensia inigualabel. Supervishon di e proyekto tabata den man di Ini Statia.

        Finalmente danki na kada tayerista, ku den práktika i bou di guia di nan dosente lo (sigui) usa e palabra i ekspreshonnan akí na un manera kreativo, pa asina tene esakinan bibu den nan skibimentu na papiamentu. Hopi éksito na tur! Dòmpereré awor!

        Kòrsou, 10 di novèmber 2017')
    this_user = User.find_by_name('Richenel Ansano')

    domperere=[
      [1,"Abogado di trepochi","uitdrukking","ja",'','',"Hende ku ta keda pusta boka, kende semper tin kontesta pa tur kos, i ta pretendé ku t’e mester gana den tur diskushon",'','','',''],
      [2,"Abrenusia! ","interhekshon","n.v.t.","Abrenunsia!",'',"Sklamashon di disgustu, spantu òf asombro. ‘Dios tene piedat!’; Abrenusia, ta den kiko mi ta haña mi akí! ",'','','',''],
      [3,"Adulto mayó","uitdrukking","ja",'','',"Hende grandi riba 65 aña",'','','',''],
      [4,"Agasaho","sustantivo","ja",'','',"Resepshon festivo pa duna honor na un hende òf un grupo",'','','',''],
      [5,"Armbòs","sustantivo","ja",'','',"Sparpòt",'','','',''],
      [6,"Awa ta finfin ","uitdrukking","n.v.t.",'','',"Áwaseru ta kai ku spat fini fini",'','','',''],
      [7,"Awor bo sa ku Viatas a bira hudiu","uitdrukking","n.v.t.","For di dia Viatas a bira hudiu, hopi hende a siña bisti.",'',"Bisá ora un hende ku no tabatin nada, yega na algu i su kabes shusha; tambe: Alpargata a haña (bisti) mea",'','','',''],
      [8,"Bagòn","sustantivo","ja",'','',"Ninichi grandi trahá di stal, e ninichi di mas balor ku tur; su balor ta sinku ninichi chikí. Tira un hende un bagòn; gaña un hende",'','','',''],
      [9,"Bai flit","uitdrukking","n.v.t.",'','',"Bai ayabanda! Bai, hòmbu! Bai keiru! Bai kore tra'i porko hala su rabu! Bai tira bubi ku slòf! (inf) Bai na moula!",'','','',''],
      [10,"Bai piska guengu","uitdrukking","n.v.t.",'','',"Pa bisa un hende e laga kai, e bai sinta un banda, e bai keiru! Guengu: sorto di kangreu chikitu di laman",'','','',''],
      [11,"Balandran","sustantivo","ja",'','',"Shimis largu i hanchu, kómodo",'','','',''],
      [12,"Balufá","verbo","n.v.t.",'','',"Sinti stoma yen ora kaba di kome, iblas",'','','',''],
      [13,"Bambusher","verbo","n.v.t.","bambuzjer",'',"Parandiá"," El a bambusher henter anochi"," Unda b’a sali bambusher awor mardugá akí? ",'',''],
      [14,"Barika yen, kurason kontentu","uitdrukking","n.v.t.",'','',"Un hende ku a kaba di kome i bebe bon, mayoria di biaha ta mashá kontentu",'','','',''],
      [15,"Barkas","sustantivo","ja",'','',"Literalmente: boto grandi  i plat, ku kua ta trese karga for di un barku grandi tera; figurativamente: un hende grandi, pisá",'','','',''],
      [16,"Bati doudou","uitdrukking","n.v.t.",'','',"Kore limpi bai",'','','',''],
      [17,"Bati bleki ","uitdrukking","n.v.t.",'','',"Hasi redu",'','','',''],
      [18,"Bati paña","uitdrukking","n.v.t.",'','',"Moda di laba paña ántes. Kant’i laman ta pone paña riba piedra di laman, ta muha nan, bati nan ku nan mes i ku palu o piedra spesial pa bati paña, pa kita shushi i laba nan; ta hiba nan kas pa hawa kita salu i habri nan riba piedra di laman den kurá pa nan seka na solo.",'','','',''],
      [19,"Beaku","athetivo","n.v.t.",'','',"Astuto, bibu, sabí manera djaka di kaña, chatiger",'','','',''],
      [20,"Belá","athetivo","n.v.t.",'','',"Belá bo ta? Ta loko bo ta? Belá mi ta? Ta bon mi kabes no ta? Den bruheria ta bela un hende sendiendo bela ‘riba su kabes’, pa hasié malu.",'','','',''],
      [21,"Belin","sustantivo","ja",'','',"Chumbu plat rondó pa tira yega serka di otro belin riba tera; distansia entre dùim ku dede di meimei ta indiká si a gana, pa risibí karchi ku portrèt di hungadó di beisbòl merikanu; wega di kolekshonista di karchi di outo, artista di sine etc.",'','','',''],
      [22,"Bemòl","sustantivo","ja",'','',"Den muzik, signo riba eskala musikal, poné na man robes di un not musikal, pa indiká ku mester toka e not ei mei tono mas abou; bisá di un situashon ménos plasentero, un hedun òf un diskushon. E kos a para bira un bemòl; (sef.) Bisá di hende (difísil) ku bo mester buska nan instrukshon di uso pa anda ku nan, pa evitá problema; Fulan ei tin masha bemòl.",'','','',''],
      [23,"Bisti luangu","uitdrukking","n.v.t.",'','',"Bisti paña di koló ku no ta kombiná ku otro",'','','',''],
      [24,"Blous","sustantivo","nee",'','',"Sustansia koló blou pa hasi paña blanku bira mas blanku bunita; Ta hunta un yuchi ku blous pa proteh’é kontra oyada (wowo pisá); Ta pon’é den awa, añadí kolonia (florida) pa baña kuné, pa evitá oyada i/o pa yama suerte.",'','','',''],
      [25,"Bo a pone mi pasa bochorno","uitdrukking","n.v.t.",'','',"Bo a pone mi pasa bèrgwensa.",'','','',''],
      [26,"Bòguibògui ","sustantivo","ja",'','',"Tipo di li di awa ku suku i kualke smak aserka, den un saku chikí di plèstik di 4 cm hanchu i 10 cm largu",'','','',''],
      [27,"Boko","sustantivo","ja",'','',"Barí grandi, di palu; Boko di ròm; figurativamente: Awor, atenshon na boko! Awor tur hende mira mi den mi kara i paga tinu!",'','','',''],
      [28,"Bolo di batrei","sustantivo","ja",'','',"Bolo di kasamentu o di risibimentu di tres dèk òf mas, generalmente batrei tabata di bolo pretu ántes",'','','',''],
      [29,"Bo lenga no a tembla?","uitdrukking","n.v.t.",'','',"Pa kontestá un hende ku a gaña",'','','',''],
      [30,"Bombokati","sustantivo","ja",'','',"Bisá di un hende kèns, idiòt",'','','',''],
      [31,"Bòñòñò","athetivo","n.v.t.",'',"ñòñitu, bònkifuè(n), bònfuè, fòñèkè","Referente na holó di deskuido, holó stinki",'','','',''],
      [32,"Bosina","sustantivo","ja",'','',"Amplifikadó di zonido i di bos humano, p.e. bosina di telefòn",'','','',''],
      [33,"Bo ta pone muchu sushi riba bo skòp ","uitdrukking","n.v.t.",'','',"Bo ke hasi muchu kos pareu",'','','',''],
      [34,"Bo tin skeit","uitdrukking","n.v.t.",'','',"Bo kabes a shusha.",'','','',''],
      [35,"Botorei","sustantivo","ja",'','',"(sef.) Lugá banda di kushina, pa warda provishon pantre); //Sorto di lugá, hopi be tambe bou di un trapi, kaminda ta warda tur sorto di kos insignifikante",'','','',''],
      [36,"Bres","sustantivo","ja",'','',"Brùg; Bo ta mira mi akí, mi ta asina bashí, ku mi no tin ni sèn pa paga bres; Hopi aña atras mester a paga tòl pa krusa brùg di ponton. Hende pia abou tabata krusa pòrnada.",'','','',''],
      [37,"Bringamosa","sustantivo","ja",'','',"Sorto di mata ku lana riba su stèngelnan ku ta kima ora mishi kuné, pone hende grawatá",'','','',''],
      [38,"Bruandashi","sustantivo","nee",'','',"Bruhamentu, konfushon ",'','','',''],
      [39,"Bubè","sustantivo","ja",'','',"Hende mashá bobo"," Hende ku ta aktua di un forma estúpido",'','',''],
      [40,"Bululú","sustantivo","nee",'','',"Desunion, pleitu ku mashá boroto, bringamentu ku hopi beheit i diskushon fuerte",'','','',''],
      [41,"Buriku no por pusta ku kabai ","uitdrukking","n.v.t.",'','',"Pober no por pusta ku riku.",'','','',''],
      [42,"Chapo","athetivo","n.v.t.",'','',"Fo’i moda, bieu, no fuerte, dekaí",'','','',''],
      [43,"Che píki!","interhekshon","n.v.t.",'','',"Ekspreshon usá ora ke gaba un hende pa algu ku el a hasi, ku bo ta haña tremendo òf ora e bisti algu ku a ked’é nèchi; Che piki! E flus ei a drecha bo tipo ruman!",'','','',''],
      [44,"Chèlèlè","verbo","n.v.t.",'','',"Papia, papia bai; papia djis pa papia",'','','',''],
      [45,"Chinchan kos","uitdrukking","n.v.t.","pa un chinchan kos…",'',"Un pa dos, pa un mínimo kos, kualke kos chikí ku pasa...",'','','',''],
      [46,"Chinchirinchi","sustantivo","ja",'','',"Para embra ku no sa para ketu, e ta keda bula bula riba suela; Su machu ta chonchorogai; (fig) Bisá di mucha ku no sa para ketu. Chinchirinchi ta warda bientu p’e bula; Bisá di un hende ku ta kambia di opinion ora ta kumbinié",'','','',''],
      [47,"Chinina kome lubidá ","uitdrukking","n.v.t.","Chinina semper ta kome lubidá ",'',"Bisá di hende ku ta lubidá masha lihé loke otro a hasi pa nan",'','','',''],
      [48,"Chokompé","sustantivo","ja","Chukumpé",'',"Hòki pa warda tur sorto di potoshi; //Kasita chikitu, skur òf kamber na mal estado, shushi. Ta ki sorto di yu por a hinka nan mama den un chokompé asina? Figurativamente: Awor mi ta den chokompé. Awor mi ta den problema grandi",'','','',''],
      [49,"Dak di shelu ta kai riba bo","uitdrukking","n.v.t.",'','',"Pa kontestá un hende ku ta gaña",'','','',''],
      [50,"Dal un slepchi","uitdrukking","n.v.t.",'','',"Drumi un ratu kòrtiku",'','','',''],
      [51,"Dèdèmèmpò","uitdrukking","n.v.t.",'','',"M’a konta bo e kos akí, pero no ripití, dera aki bou, shete pia bou di tera",'','','',''],
      [52,"Den un fregá di wowo","uitdrukking","n.v.t.",'','',"Den un ratu asina"," masha lihé mes",'','',''],
      [53,"Dera tròt","uitdrukking","n.v.t.",'','',"Kore outo duru; primi pia kompletamente riba tròt di un vehíkulo di motor, di manera ku esaki ta kue un velosidat haltu",'','','',''],
      [54,"Diabel a kibra koko den su kara","uitdrukking","n.v.t.",'','',"E no tin bèrgwensa"," tambe: Su kara no tin wesu.",'','',''],
      [55,"Di gañagaña ","uitdrukking","n.v.t.",'','',"Di tuma hasi, no di bèrdat, sino di wega, di ròl, di fantasia",'','','',''],
      [56,"Dilanpatras","athetivo","n.v.t.",'','',"(di Boneiru) Dilanti patras, padilanti patras, p’eilanti patras",'','','',''],
      [57,"Di pursi","uitdrukking","n.v.t.",'','',"Di mes, 'eigenlijk', despues di tur kos, naturalmente, riba su mes kaba, tòg",'','','',''],
      [58,"Diósolopaga","uitdrukking","n.v.t.",'','',"Ekspreshon di gratitut na Kreador",'','','',''],
      [59,"Djaka di batrei","uitdrukking","n.v.t.",'','',"Sòldánan hulandes ku ántes tabata biba den Fort Amsterdam na Willemstad (Ta referí na nan komo protestant blanku, grupo di hende ku tambe a forma nos komunidat)",'','','',''],
      [60,"Djamars tin drel","uitdrukking","n.v.t.",'','',"Hopi aña atras tabatin drel na Punda tur djamars.",'','','',''],
      [61,"Djindja","verbo","n.v.t.",'','',"Rabia, bira furioso. Djindja (un piská) su sais ta mediano te mas grandi. Ta haña nan den awanan tropikal, no muchu hundu. Komo defensa nan ta guli awa òf airu i span nan kurpa, hasié mas rondó. Otro defensa ta nan spiñanan ku ta punta pafó ora nan reis. Tin djindja ta venenoso, ku venenu mas potente ku sianide.",'','','',''],
      [62,"Djingueri","athetivo","n.v.t.","djingueli",'',"Bibitu, kontentu, animá, sumamente alegre (generalmente ta bisa esaki di mucha)",'','','',''],
      [63,"Djuku","sustantivo","ja",'','',"Nechi rondó pretu di un mata. Sa traha prenda di dje (hanger pa pasa den kadena); //Opheto rondó di glas pa wega di ninichi; //Hende pretu grandi, grueso, masha skur; //Tambe: un hende bibu, astuto, djaka di kaña // Kantika despues di 1863: ‘Kaiman djuku, djuku kaiman […] awor ta shon mes lo laba koprá… Kaiman djuku, djuku kaiman’.",'','','',''],
      [64,"Dòndersla","sustantivo","ja",'','',"Mucha poko mala mucha; tambe: bisá di un mucha (hóben) emprendedor, yen di pèp",'','','',''],
      [65,"Dòriá pegá","uitdrukking","ja",'','',"Bisá ora paña di un hende muhé keda visiblemente pegá meimei di su dos blatnan di atras",'','','',''],
      [66,"Drandran","sustantivo","nee",'',"mèkèmèkè","Shushi den huki di wowo ora lanta mainta",'','','',''],
      [67,"Drel","sustantivo","ja",'',"parada militar","Marcha na kompas di militar",'','','',''],
      [68,"Dúndula","verbo","n.v.t.",'','',"Kana bai bini hasi pida pida kos",'','','',''],
      [69,"El a bai den su stimpat","uitdrukking","n.v.t.",'','',"El a bai na de dònder"," El a frakasá totalmente.",'','',''],
      [70,"Enditu ","athetivo","n.v.t.",'','',"Eksaktamente asina"," presis meskos",'','',''],
      [71,"Enganche","sustantivo","nee",'','',"Tempu sine a hasi su entrada na Kòrsou tabatin nochi di enganche, bo ta paga pa un i risibí dos entrada pa mira pelíkula",'','','',''],
      [72,"E ta na pan pidí, funchi halá, (kasabi hòrtá, arepa fiá)","uitdrukking","n.v.t.",'','',"El a bira pober.",'','','',''],
      [73,"E ta poko vra ","uitdrukking","n.v.t.",'','',"Bisá di un hende kende su kabes no ta muchu bon, e ta hasi kos straño.",'','','',''],
      [74,"Èshi porèshi ","uitdrukking","n.v.t.",'','',"Kuminsamentu di un rima di mucha. Den un grupo, ora un mucha saka bientu, pa determiná ken ta e ‘kulpabel’, ta skohe dos mucha i entre nan ta lòt. Nan ta para kara pa otro i e lider ta bati man riba kada un su pechu na turno, miéntras e ta bisa: 'Èshi porèshi di toka maraka di skeins kaoka, èshi de puf!' Tambe, na Aruba: '... di skeins di kahon...'. E final sa varia ku: '...èshi porèshi, de, ka, puf!' Esun ku sali na 'puf' ta sali liber di tur kulpabilidat i e lider ta sigui lòt entre e mucha ku a keda aden i un otro mucha, pa mira ken ta haña bürt pa e wega sigui.",'','','',''],
      [75,"E yu ku no tende di su mama, at’é den boka di kolebra","uitdrukking","n.v.t.",'','',"Esun ku no ke skucha bon konseho, mester karga e konsekuensianan.",'','','',''],
      [76,"Fansifun","sustantivo","nee","fansifú",'',"(sef) Eksagerashon, makakeria, babel, buya",'','','',''],
      [77,"Fèrtada","sustantivo","ja",'','',"Plato di webu hasá, mas o ménos manera òmelèt, pero mas kompakto, mas diki, prepará a base di sierto ingrediente ku por varia; webu batí i hasá riba kabaron, karni kòrtá chikitu, tin biaha piská, banana ku keshi òf bèrdura",'','','',''],
      [78,"Floho manera Parnas","uitdrukking","n.v.t.",'','',"Masha floho mes",'','','',''],
      [79,"Frèskòt","sustantivo","ja",'','',"Delantal, pa protehé paña pa e no shusha",'','','',''],
      [80,"Friu ta kòrta","uitdrukking","n.v.t.",'','',"Bisá ora ta hasi masha friu",'','','',''],
      [81,"Gòt","sustantivo","ja",'','',"Kanal entre laman i saliña, ku por habri pa laga awa drenta saliña i ta sera bèk pa salu por forma den saliña",'','','',''],
      [82,"Gordiflonchi","athetivo","n.v.t.",'','',"Forma simpátiko pa yama un hende un poko gordo",'','','',''],
      [83,"Grita sin miserikòrdia","uitdrukking","n.v.t.",'','',"Grita masha duru mes, sin kompashon",'','','',''],
      [84,"Hala mara","uitdrukking","n.v.t.",'','',"Forma un unidat, uni forsa pa huntu por enfrentá problema",'','','',''],
      [85,"Hala na rant ","uitdrukking","n.v.t.",'','',"Keda leu ",'','','',''],
      [86,"Haña bo den un perkanse","uitdrukking","n.v.t.",'','',"Topa ku un difikultat, un situashon fastioso, un desapunte",'','','',''],
      [87,"Haña chamba ","uitdrukking","n.v.t.",'','',"(sef.) Keda sin haña invitashon pa un fiesta na kas di amigunan",'','','',''],
      [88,"Haña djimbi","uitdrukking","n.v.t.","Haña djimpi",'',"Haña steipi"," tambe: rabia masha pisá",'','',''],
      [89,"Hasi fishi di indjan","uitdrukking","n.v.t.",'','',"Lanta bai asina kaba di kome",'','','',''],
      [90,"Hende pete ","uitdrukking","n.v.t.",'','',"Bisá di hende ku tin dos man robes"," nan no tin abilidat pa hasi e kosnan di mas simpel ku tin.",'','',''],
      [91,"Hera Michi, kohe Mèmè ","uitdrukking","n.v.t.",'','',"No logra e meta original, pero saka probecho tòg",'','','',''],
      [92,"Hinka man den wowo di Dios","uitdrukking","n.v.t.",'','',"Keha, reklamá, kik sin ningun motibu; Bo no mester hinka man den wowo di Dios.",'','','',''],
      [93,"Hole baf","uitdrukking","n.v.t.",'','',"Tin mal aliento",'','','',''],
      [94,"Hole chubatu","uitdrukking","n.v.t.",'','',"Tin mal holó di sodó bou di brasa",'','','',''],
      [95,"Holó!","interhekshon","n.v.t.",'','',"Sklamashon di asombro, di sorpresa (di Aruba: Oh Lord!)",'','','',''],
      [96,"Hunga peik","uitdrukking","n.v.t.",'','',"Hunga ninichi",'','','',''],
      [97,"Hunga pishibamba","uitdrukking","n.v.t.",'','',"Sèks o intento di sèks entre mucha ku físikamente ainda no ta seksualmente desaroyá",'','','',''],
      [98,"Kabei alabròshi","uitdrukking","n.v.t.",'','',"Peñá ku tur kabei mandá patras",'','','',''],
      [99,"Kabe’i boto ","uitdrukking","n.v.t.",'','',"Parti dilanti di un boto"," tambe: left. Pidi un kabe’i boto"," duna un kabe’i boto"," haña un kabe’i boto"," tuma un kabé’i boto serka un òf mas hende ku ta transportá bo hiba bo kaminda bo ke bai."],
      [100,"Kabes di Kiña","uitdrukking","n.v.t.",'','',"Bisá di hende bobo",'','','',''],
      [101,"Kabes habrí","uitdrukking","n.v.t.",'','',"Bisá di un persona ku no ta serio, sino frívolo",'','','',''],
      [102,"Ka’i heru ","sustantivo","ja",'','',"Seif, klùis",'','','',''],
      [103,"Kakabú","sustantivo","nee",'','',"Shushi di baka seku usá komo insektisida natural"," Ta kima e kakabú seku i lag’e huma pariba di kas pa kore ku insekto",'','',''],
      [104,"Kalèmbè","sustantivo","ja",'','',"Kramp kompañá pa rel di friu",'','','',''],
      [105,"Kambou","athetivo","n.v.t.","kòmbou",'',"Kròm, malu, mankaron; Sapatu kambou; Ántes nan tabata bisa, ku ora un mucha ta demasiado gordo i fòrs’é kana promé ku su tempu, su pianan ta bira kambou (kòmbou), e pianan ta deformá (pia O).",'','','',''],
      [106,"Kaminda mi mira bo pia, mi ke mira bo kabes ","uitdrukking","n.v.t.",'','',"E hende na palabra ta deseá di mira tal hende na kende e ta dirigí palabra, den su ka’i morto.",'','','',''],
      [107,"Kamisa di ónsebara","uitdrukking","n.v.t.",'','',"Kamisa di 9,24 meter; Kualke situashon den kua un hende ta kompliká su bida innesesariamente; El a hinka su kurpa den un kamisa di ónsebara sin ku e por sali afó.",'','','',''],
      [108,"Kara halá","uitdrukking","n.v.t.",'','',"Kara ku ta mustra klaramente ku e hende a bira flaku òf posiblemente e ta tristu",'','','',''],
      [109,"Kara vonviño","uitdrukking","n.v.t.",'','',"Kara tur na ploi",'','','',''],
      [110,"Kaster pushi!","interhekshon","n.v.t.",'','',"Salú! Deseo ku un hende ta ekspresá na un hende ku a nister",'','','',''],
      [111,"Kataklismo","sustantivo","ja",'','',"Desaster, katastròf, kalamidat",'','','',''],
      [112,"Katochi","sustantivo","nee",'','',"Sorto di wega di number ilegal, spesialmente na Aruba, ku despues a bira legal",'','','',''],
      [113,"Kenken pi’e wesu","uitdrukking","n.v.t.",'','',"Kontesta komo argumento trivial ora hende puntra ‘Ken?’",'','','',''],
      [114,"Kenkus","sustantivo","nee",'','',"(di hulandes: 'kinkhoest') Enfermedat di mucha chikitu ku masha tosamentu debí na un infekshon.",'','','',''],
      [115,"Kèrèkèntènchi","uitdrukking","n.v.t.",'','',"Kantika tradishonal: ‘T’asina nos ta balia kèrèkèntènchi, kèrèkèntènchi, t’asina nos ta balia ‘kèrèkèntèèènchi’. ’T’asina nos ta kome, kanta, hari etc, semper hasiendo e gestonan ku ta kompañá e kantamentu.",'','','',''],
      [116,"Kibra zjuzjum","uitdrukking","n.v.t.",'','',"(sef.) Kibra yuna, esta stòp di yuna; Zjuzjum ta yuna, apstené di kome i di bebe pa motibunan religioso na okashon di Yòm Kipur, e dia mas sagrado di religion hudiu",'','','',''],
      [117,"Kinikintèr","athetivo","n.v.t.",'','',"Kaweta",'','','',''],
      [118,"Kiriwichi","sustantivo","nee",'','',"Sobrá di kuminda ku ta keda pegá entre e djentenan; // Shushi entre e blatnan di atras; // Na Aruba i Boneiru: lima, yerba di laman",'','','',''],
      [119,"Klesté","sustantivo","ja","klestek",'',"Labá di tripa, tambe e opheto usá pa realisá e labamentu",'','','',''],
      [120,"Klishé","sustantivo","ja",'','',"Palabra òf ekspreshon usá ku tantu frekuensia, ku e ta pèrdè su efektividat, e ta bira laf, gastá (den propaganda p.e.: di Bándariba te Bándabou…, unda ku bo bira…, etc.)",'','','',''],
      [121,"Koketon","athetivo","n.v.t.","Kokèt",'',"Bisá di un hende ku ta purba agradá o atraé e sekso opuesto pa puru vanidat i ku medionan debidamente studiá",'','','',''],
      [122,"Kombitu sin noi","uitdrukking","n.v.t.",'','',"Un hende ku a bai fiesta sin ta invitá. Tambe ta us’é ora un hende klaramente no ta sintié kómodo"," M’a sinti mi manera kombitu sin noi"," Manera galiña sin nèshi.",'',''],
      [123,"Kombles","sustantivo","ja",'','',"Mucha muhé, muhé di bo frei òf di bo partner ta bo kombles",'','','',''],
      [124,"Kome manera hos ta trèk","uitdrukking","n.v.t.",'','',"Kome masha hopi mes",'','','',''],
      [125,"Konfó","sustantivo","ja",'','',"Opheto trahá di heru bashá, den kua ta sende palu pa kushiná riba kandela di karbon",'','','',''],
      [126,"Konosenshi","sustantivo","nee",'','',"Hiba konosenshi"," Hiba kumindamentu.",'','',''],
      [127,"Kopioso","athetivo","n.v.t.",'','',"Hopi kantidat, abundante. Bisá tambe di algu ku no ta komun i koriente, algu un poko diferente",'','','',''],
      [128,"Korin koran","uitdrukking","n.v.t.",'','',"Wega di ‘skonde faha’, ku mucha hòmber tabata hunga den pouze na Hendrikschool",'','','',''],
      [129,"Krendiospader!","interhekshon","n.v.t.",'','',"Sklamashon di asombro",'','','',''],
      [130,"Krepchi","athetivo","n.v.t.",'','',"Iritabel, fo’i ekilibrio, kla pa rabia pa kualke kos chikitu",'','','',''],
      [131,"Kuidou bo no mira bo tata sunú bo dilanti","uitdrukking","n.v.t.","Kuidou bo no mira bo suegu/diabel sunú bo dilanti",'',"Mihó bo stòp di gaña.",'','','',''],
      [132,"Kumpr’é pa bobo","uitdrukking","n.v.t.",'','',"Ta kere bo ta kere ku e ta bobo.",'','','',''],
      [133,"Kushina ta na rou","uitdrukking","n.v.t.",'','',"No tin kuminda den kushina"," no a kushiná awé den e kas akí.",'','',''],
      [134,"Laipo!","interhekshon","n.v.t.","laibo!",'',"Palabra usá na chansa ora un hende den bo besindario saka un bientu (puya). Bo ta tek e na su brasa, bisa: ‘Laipo!’, òf ‘Laibo!’",'','','',''],
      [135,"Laman ganchu","sustantivo","nee",'','',"Laman afó",'','','',''],
      [136,"Lantada","verbo","n.v.t.",'','',"Dal hende un daks, kue hende kabes abou",'','','',''],
      [137,"Lata lata ","uitdrukking","n.v.t.",'','',"Yen yen, bon kargá",'','','',''],
      [138,"Lebelebe","athetivo","n.v.t.","lèbèlèbè",'',"Masa ku ora bo ful’é, e ta manera sleim",'','','',''],
      [139,"Lele katunbòm ","uitdrukking","n.v.t.",'','',"Tabata lele e flornan di palu di katunbòm, di manera ku e simianan ta keda den bòm, pa na final di e proseso yena kusinchi ku nan.",'','','',''],
      [140,"Leng’afó","athetivo","n.v.t.",'','',"Morto kansá",'','','',''],
      [141,"Lenga manera sentebibu ","uitdrukking","n.v.t.",'','',"Bisá di hende ku lenga skèrpi ku ta ofendé hende ku palabra sin pordon",'','','',''],
      [142,"Letelete","athetivo","n.v.t.",'','',"Bisá di hende ku ta hinka boka den tur kos",'','','',''],
      [143,"Levelekòl","verbo","n.v.t.","Lembe lakòl, Leba lekòl",'',"(sef.) Lanta kurpa, hisa bela, laga kai, muf; Ta bisa asina pa indiká ku a yega ora di laga tumba, hala kita for di un fiesta, komida o loke sea, Ta ora di levelekòl, lembe lakòl òf leba lekòl.",'','','',''],
      [144,"Lombra hèspu ","uitdrukking","n.v.t.",'','',"Balia kurpa asina pegá ku otro, ku hèspu di e kabayero ta haña un bon lombrá",'','','',''],
      [145,"Lombra wowo ","uitdrukking","n.v.t.",'','',"No por pega soño"," // Sinta mira leu"," // No hasi nada.",'',''],
      [146,"Luangu","athetivo","n.v.t.",'','',"Koló ku no ta kombiná ku otro",'','','',''],
      [147,"Lushi klas","sustantivo","ja",'','',"Skol pa mucha di kuater i sinku aña; ‘kleuterklas’, ‘fröbelklas’",'','','',''],
      [148,"Mamparia kutu ","sustantivo","ja",'','',"(di Boneiru) Sirena"," mitar hende mitar piská ku ta sedusí hende hòmber",'','',''],
      [149,"Marianchi no ta mira di dje, e ta bisa di Mona ta largu","uitdrukking","n.v.t.",'','',"Hende ta mira defekto di otro, anto ta keda sin mira di nan mes.",'','','',''],
      [150,"Muska morto","uitdrukking","n.v.t.",'','',"Hende poko laf, sin grasia",'','','',''],
      [151,"Ni ku kachó di polis bo no ta haña mi bèk ","uitdrukking","n.v.t.",'','',"Reakshon ku firmesa ora bo pleita p.e. ku bo frei, bo kasá òf ku kualke otro hende, pa nan sa ku bo no ta bini bèk mas",'','','',''],
      [152,"No bai largu!","interhekshon","n.v.t.",'','',"Pasa pronto serka mi atrobe!",'','','',''],
      [153,"Ñòñèkè","athetivo","n.v.t.",'','',"(sef.) Bisá di mucha malkriá ku ta keda ñèñèñè",'','','',''],
      [154,"Ora baka hoga na pos ta dèmpl’é","uitdrukking","n.v.t.",'','',"Despues ku a pasa desgrasia ta tuma medida.",'','','',''],
      [155,"Ora galiña ta kontentu, warawara ta kome su yunan","uitdrukking","n.v.t.",'','',"Despues di un alegria inmenso ta bini tristesa.",'','','',''],
      [156,"Orketa","sustantivo","ja",'','',"Fòrki grandi di dos o mas djente pa e.o. hisa yerba seku, montoná mèst i hasi otro trabou den kunuku; // parti di un palu kaminda e tronkon i un rama diki ta forma un huki skèrpi; //palu ku na un ekstremo ta habri formando dos punta i ku ta usa komo refuerso pa sostené un òf otro kos; tambe: palu pa traha chincha ",'','','',''],
      [157,"Palalá","sustantivo","nee",'','',"Shushi di bestia, abundante, manera di baka p.e. ",'','','',''],
      [158,"Pasa pa sawaka"," baha na (pa) sawaka"," bai sawaka","uitdrukking","n.v.t.",'','',"Muri, bai sosegá; Ayó sawaka! Tur kos ta pèrdí!",'',''],
      [159,"Patapuf","athetivo","n.v.t.",'','',"(sef) Bisá di un hende gordo, bashá; Bisá tambe ora p.e. un hende laga su kurpa kai den un stul kómodo; El a kai patapuf riba e sofá.",'','','',''],
      [160,"Patatus","sustantivo","nee",'','',"Ora un hende haña sea un atake di kurason o serebral.",'','','',''],
      [161,"Pegadito","sustantivo","ja",'','',"Paña pertá, tantu karson komo saya, pegá na kurpa",'','','',''],
      [162,"Peiki","sustantivo","ja",'','',"Mucha muhé; Ora ta broma ku un frei (mucha muhé) bunita, meskos ku hende ku ta prònk ku nan kachó pekines (pekines → peiki; 1980+).",'','','',''],
      [163,"Pèrdè San Huan","uitdrukking","n.v.t.",'',"Pèrdè (a)riba","Lanta fo’i soño lat",'','','',''],
      [164,"Pèrèmpèmpèn","athetivo","n.v.t.",'',"fututu, diguidigui","Bisá di un situashon (ekonómiko) basta malu moral- o materialmente; negoshi ku ta bai malu, kos ku ta baitu, situashon ku ta fregá, abominabel",'','','',''],
      [165,"Pishituar","sustantivo","ja",'','',"Mi ta bai dal un pishituar; Bieunan tabata bisa asina, esta na un manera nèchi, ora nan ke bai oriná. ",'','','',''],
      [166,"Planbarí","athetivo","n.v.t.",'','',"Blo bashí, sin niun sèn chikí",'','','',''],
      [167,"Playa","sustantivo","ja",'','',"Kant’i laman"," // Lugá (na kas den kurá) pa seka i laga paña blikia riba piedra di laman"," //Nòmber di kariño ku arubano i bonerianonan a duna kapital di nan respektivo islanan",'',''],
      [168,"Plendu ","verbo","n.v.t.","plènder",'',"Nan a (plendu) plènder e kas òf: Alberto semper ta (plendu) plènder mi (e ta kita tur mi sèn).",'','','',''],
      [169,"Poltrona","sustantivo","ja",'','',"Stul di palu, konfortabel, ku brasa i pará",'','','',''],
      [170,"Pòmpòn","sustantivo","ja","pònpòn",'',"Adorno pa den kabei, riba paña, riba sapatu; tambe: pa indiká algu ku ta di kalidat inferior, algu ku no ta nèchi akabá.",'','','',''],
      [171,"Pone lenga na papiòt","uitdrukking","n.v.t.","pone boka na papiòt",'',"Prepará mentalmente ora ta bai papia un lenga strañero"," Ora un hende ta kla pa e bai kome un kuminda ku e tin masha gana di kome.",'','',''],
      [172,"Portavianda","sustantivo","ja",'','',"Sèt di resipiente rondó, di granit o di bleki, poné riba otro i ku ta hak kada banda den un man kargadó, pa transportá kuminda",'','','',''],
      [173,"Pos di pia","sustantivo","ja",'','',"Pos ku su boká ta riba suela i tantu hende komo bestia por yega pa bebe awa",'','','',''],
      [174,"Pulsera","sustantivo","ja",'',"brasalèt, brazilèt","Armbant, balentina ",'','','',''],
      [175,"Ral","athetivo","n.v.t.",'','',"Sensashon di debilidat pa falta di kome òf bebe algu",'','','',''],
      [176,"Ranka figura","uitdrukking","n.v.t.",'','',"Forma chistoso pa: saka pòrtrèt",'','','',''],
      [177,"Raton di anochi","sustantivo","ja",'','',"(hulandes: vleermuis) Tipo di mamífero ku tin entre su tronko i su miembronan dilanti fuertemente alargá, un flishi ku ta hasi ku e por bula",'','','',''],
      [178,"Rébuzak","verbo","n.v.t.","Rébusak, Rébusai",'',"Reprendé un hende na mal òrdu"," El a rébuzak mi"," kaska su ròk",'',''],
      [179,"Refresko","sustantivo","nee",'','',"Limonada",'','','',''],
      [180,"Rèk pia","uitdrukking","n.v.t.",'','',"Lanta para fo’i stul pa kana un tiki"," tambe: sinta pia na laria pa sosegá",'','',''],
      [181,"Ribirishi","sustantivo","nee",'','',"Hasimentu di redu, redashi, hinkamentu di palu bou di kandela ",'','','',''],
      [182,"Ròshi","verbo","n.v.t.","Ròshi kaya ",'',"Kore paranda ",'','','',''],
      [183,"Roxy pòrnada","uitdrukking","n.v.t.",'','',"Ora un mucha muhé ta sinta pia habrí, òf e tin un eskote eksagerá bistí, ta manera un show grátis e ta duna (Roxy ta nòmber di un teater di sine na Kòrsou ku no ta eksistí mas); Tabata bisa tambe ku ‘e ta saka portrèt’.",'','','',''],
      [184,"Rushi di uña ","sustantivo","nee",'','',"Pintura di uña",'','','',''],
      [185,"Rushi di boka ","sustantivo","nee",'','',"Lipstik",'','','',''],
      [186,"Sakseilu","verbo"," athetibo","n.v.t.",'','',"Manera pa indiká ku algu ta poko skèins, asimétriko; E fli ta sakseilu; Ora bo no por kana riba un liña règt, ta kana di un forma no stabil, moviendo sin kontròl di un banda pa otro, bo ta kana sakseilu; Bisá tambe ora un vehíkulo ta kore zigzag riba kaminda",'','',''],
      [187,"Saldinchi na bleki","uitdrukking","n.v.t.",'','',"Hende pèrtá riba otro",'','','',''],
      [188,"Sanpèt","uitdrukking","n.v.t.","sampèt",'',"Sampèt kokoí"," tambe: vipé kokoí"," Amèn"," A kaba"," Kla ta!"],
      [189,"Sa puntra morto si e ke respòns òf si e ke santana òf si e ke bela?","uitdrukking","n.v.t.",'','',"Kontesta di un persona ku no por nenga loke e tin masha gana di haña na e momento ei",'','','',''],
      [190,"Sarna ku gustu no ta pika","uitdrukking","n.v.t.","Sarna ku gustu no ta pika i si e pika e no ta mortifiká ",'',"Pa indiká ku ora un hende emprendé algu, konsiente i di su propio gustu, ni maske e topa ku kontratempu, e no ta deskurashá.",'','','',''],
      [191,"Sendé sendé","uitdrukking","n.v.t.",'','',"Ekspreshon di un hende ku ke pa hende sa ku e ta bei bei, bon na tinu. Mi ta sendé sendé, al tanto di tur kos ku ta pasa i mi ta mustra esei den mi estilo di bisti i di papia.",'','','',''],
      [192,"Serena","sustantivo","nee",'','',"Humedat di atmósfera durante anochi i mardugá",'','','',''],
      [193,"Sergeant majoor ","sustantivo","ja",'','',"Beinam pa hende ku gusta manda",'','','',''],
      [194,"Sènguènè","sustantivo","ja",'','',"Skèrf di glas pegá na rabu di fli, nèpe di glas; // Muhé peligrosamente skèrpi; //Tambe: usá komo apelativo di kariño pa bo dushi; Mi sènguènè, mi djèguèdjèguè",'','','',''],
      [195,"Shimuhé","sustantivo","ja",'','',"Homoseksual",'','','',''],
      [196,"Shuata","verbo","n.v.t.",'','',"Intoksiká o kousa intoksikashon pasobra a kome algu dañá",'','','',''],
      [197,"Si e rabia, e morde su rabu","uitdrukking","n.v.t.",'','',"Reakshon pa mustra ku rabiamentu di e hende ei no ta afektá bo",'','','',''],
      [198,"Sinkuria","sustantivo","ja",'','',"Sombré di kabana pa hende hòmber, opheto ku a haña su nòmber debí na su preis (75 sèn, sínkuria); Den un kantika, énfasis ta kai riba e ‘u’: ‘sinkuria t’un bon sombré’, pa mantené ritmo di e kantika.",'','','',''],
      [199,"Sin pariba, sin pabou","uitdrukking","n.v.t.","sin pariba ni pabou",'',"Blo bashí, sin niun sèn chikí; sin un lugá pa bai",'','','',''],
      [200,"Skeliu","athetivo","n.v.t.",'','',"Bisá di palu ku a blas òf ku no ta haks montá",'','','',''],
      [201,"Skit","verbo","n.v.t.",'','',"Hala kita;//Laga un kos kai sin bo por yuda: e kòpi a skit fo’i mi, kai kibra; //Eyakulá",'','','',''],
      [202,"Skrámulè","sustantivo","ja",'','',"Literalmente webu ruròm òf figurativamente, bisa un kos di un forma bruhá, konfuso.",'','','',''],
      [203,"Slabeis","athetivo","n.v.t.",'','',"Bisá di mucha chikitu ku tabatin soño pero komo su soño a kita, el a bira krepchi; Chita tabatin soño pero ya el a bira slabeis.",'','','',''],
      [204,"Slèmbèslèmbè","athetivo","n.v.t.",'','',"Flaku, sin grasia",'','','',''],
      [205,"Slep den baba","uitdrukking","n.v.t.",'','',"Kere o kai pa mentira di otro",'','','',''],
      [206,"Slep sali ","uitdrukking","n.v.t.",'','',"Sali sin niun hende ripará",'','','',''],
      [207,"Smelap","athetivo","n.v.t.",'','',"Hende poko konfiabel ku ta bini bo ku triki shushi; tambe na chansa usá: Bo tio ta un smelap, pasobra masha dia e no a puntra pa mi.",'','','',''],
      [208,"Sobrekama","sustantivo","ja",'','',"Paña pa habri riba laken, pa kaba di drecha kama nèchi; tambe ántes: plaka di papel koló blanku ku kòrá, na balor di un florin",'','','',''],
      [209,"Spièrta mi ","uitdrukking","n.v.t.",'','',"Literalmente: Lanta mi for di soño"," figurativamente: avisá mi",'','',''],
      [210,"Spirit'i bòkel","uitdrukking","n.v.t.",'','',"Bisá di un hende masha flaku"," Bòkel: piská konservá den salu",'','',''],
      [211,"Spòrt","athetivo","n.v.t.",'','',"Nèchi"," El a keda spòrt den su flus blou skur.",'','',''],
      [212,"Start sali","uitdrukking","n.v.t.",'','',"Nòmber popular pa un tipo di slòf di rùber importá ku tabata na moda na Kòrsou; Tabata pasa dede grandi i esun banda dje meimei di lenga di e slòf, i bo ta kla pa ‘start sali’ bai lihé.",'','','',''],
      [213,"Steira","sustantivo","ja",'','',"Kama di pushi ku ta habri abou pa drumi ariba",'','','',''],
      [214,"Stèkòm","sustantivo","ja",'','',"Vèt pa hunta den kabei pa e peñá wanta",'','','',''],
      [215,"Stelchi","sustantivo","ja",'','',"Di hulandes: ‘Stilletje’; stul di mahòk, p.e. banda di kama, ku ta karga un wea di un orea, ku hende por usa komo wc",'','','',''],
      [216,"Stet skol ","verbo","n.v.t.",'','',"Falta skol intenshonalmente",'','','',''],
      [217,"Streif","sustantivo","ja",'','',"Plato di webu hasá manera òmelèt ku por tin p.e. bakiou, tuna, etc. pa hasi e òmelèt mas riku",'','','',''],
      [218,"Stul di ki mi ke hasi","uitdrukking","n.v.t.",'','',"Stul di zoya importá na Kòrsou, ku a bini komo no tabatin esun ku originalmente tabata fabriká na Viena, esun ku pueblo tabata kustumbrá kuné. A bini esunnan ku speilu, tantu stul di zoya komo stul pará. Pueblo a reakshoná e ora ei: ‘Ki mi ke hasi’.",'','','',''],
      [219,"Subi zòlder","uitdrukking","n.v.t.",'','',"Drenta menopousa, tambe: bira inkapas (debí na edat) pa realisá akto seksual; òf: pèrdè interes den aktividat seksual, loke ta konta pa hende hòmber i tin biaha pa hende muhé ku a stòp ku menstruashon",'','','',''],
      [220,"Tapá","sustantivo","ja",'','',"Kos di kome di grasia ku hende ta manda (di regalo) den un tayó òf den un wea tapá, nèchi lorá den un paña; // Tambe bisá di hende mashá bobo mes",'','','',''],
      [221,"Tembleki","sustantivo","nee",'','',"Atake físiko kaminda e persona ta keda tembla",'','','',''],
      [222,"Traskuarto","sustantivo","ja",'','',"(sef.) Kamber di troka paña, banda di kamber di drumi",'','','',''],
      [223,"Trepochi","sustantivo","ja",'','',"Resipiente di bleki (ántes) òf di otro sorto di metal den kua ta trèk te òf otro yerba, òf trèk kòfi",'','','',''],
      [224,"Trifulka","sustantivo","nee",'','',"(sef.) Bruandashi, diskushon, pleitu, babel. Trastorno i konfushon entre vários persona",'','','',''],
      [225,"Un kayente, un friu","uitdrukking","n.v.t.",'','',"Elogio i alabes reproche",'','','',''],
      [226,"Un skat di kos ","uitdrukking","n.v.t.",'','',"Un tou di kos"," un kantidat di kos",'','',''],
      [227,"Un pinga","sustantivo","n.v.t.",'','',"Un gota; Tambe: djis un ratu, masha tiki ratu; falta un pinga pa… para un pinga pa… ta hera un pinga pa…// Si no yobe lo pinga. Haña un parti òf algu di tur manera, sea hopi òf tiki",'','','',''],
      [228,"Wabi","sustantivo","ja",'','',"Outo bieu"," tambe usá ora bo ke bisa ku bo no ta sinti bo kurpa shen porshento. Awe e kurpa ta wabi"," Tambe: Awe e kurpa ta wadjo.",'',''],
      [229,"Wadjo","athetivo","n.v.t.",'','',"Falsu; Bisá di muzik; Flùit wadjo; kanta wadjo; Tambe pa deskribí situashon di salú: Awe mi no ta sinti muchu bon, e kurpa ta wadjo; tambe: E kurpa ta wabi.",'','','',''],
      [230,"Waiki","sustantivo","ja",'','',"Paña chikí; ferbant di luna estilo bieu, esta pida paña ku hende muhé tabata usa (re-usabel) ántes ora nan ta na regla",'','','',''],
      [231,"Wak bo n’ poncha","uitdrukking","n.v.t.",'','',"Mira pa bo no keda desepshoná.",'','','',''],
      [232,"Wangalan","sustantivo","ja",'',"piskalat, prizòn","Lugá kaminda ta sera hende ku a kometé delito",'','','',''],
      [233,"Wantomba","sustantivo","ja",'','',"Spantapara; pòpchi di palu tamaño di un adulto ku paña bistí ku ta waya den bientu, poné den kunuku plantá pa spanta i kore ku para; Keda manera un wantomba: Parse spantapara; Hasi ko’i wantomba: Hasi bo mes ridíkulo; Hasi wantomba: Baha bai ketu ketu",'','','',''],
      [234,"Watapana","sustantivo","ja",'',"Dividivi","Palu ku blachi dòbel kompuesto di 0,7 cm. i flor na tròshi. Su bonchi ta diki ikrùl. Ta us’é pa kurti kueru kuné, esta frega riba kueru di bestia te hasié suave, di moda ku por prosesá e kueru.",'','','',''],
      [235,"Wendro","verbo","n.v.t.",'','',"(di hulandes: winddroog)"," laga un kos seka den bientu",'','',''],
      [236,"Wendrùif","sustantivo","ja","wendrèif",'',"Fruta di palu di wendrùif",'','','',''],
      [237,"Wowo di falki","uitdrukking","n.v.t.",'','',"Masha bon wowo",'','','',''],
      [238,"Wow’i kariño","uitdrukking","n.v.t.",'','',"Kinip’í wowo",'','','',''],
      [239,"Yongotá","verbo","n.v.t.",'','',"Sinta rudia doblá, di moda ku bo atras ta keda riba bo hilchinan sin mishi ku suela",'','','',''],
      [240,"Yora malai","uitdrukking","n.v.t.",'','',"Lamentá algu ku a pasa, ku bo por a evitá pasobra por ehèmpel a taha bo; tambe: yora amargamente, lamentá loke bo a hasi o keda sin hasi, pero ya e ora ei ta lat",'','','',''],
      [241,"Yòrki","sustantivo","nee",'','',"Karni di kabritu, karné o porko salgá i seká pa konsumo",'','','',''],
      [242,"Yu sin mama","uitdrukking","n.v.t.",'','',"Bisá di un hende desampará",'','','',''],
      [243,"Zamba ta pasa sket","uitdrukking","n.v.t.",'','',"Bisá ora saya di abou ta pasa. Zamba ta un sorto di kama simpel, trahá ku palu di kadushi di dos pa tres inch diki, riba kuater pia, tur di mes midí, ku su bòm tambe di palu di kadushi òf di lona. Sket ta e skòt ku tabata sirbi pa dividí kamber fo’i sala di un kas humilde. Ora e zamba ta mas largu ku e skòt, hende ta mir’é meskos ku ta mira e saya di abou ku ta pasa.",'','','',''],
    ]

    # ["nummer","lemma","woordsoort (uitdrukking, of 1 van de woordsoorten)","telbaar (ja, nee, n.v.t)","Variatie(s)","Synoniem(en)","beschrijving",'','','',''],
    # {0=>"nummer", 1=>"lemma", 2=>"woordsoort (uitdrukking, of 1 van de woordsoorten)",
    #  3=>"telbaar (ja, nee, n.v.t)", 4=>"Variatie(s)", 5=>"Synoniem(en)", 6=>"beschrijving",
    #  7=>"", 8=>"", 9=>"", 10=>""} (toevoegen aan beschrijving)
    domperere.each do |domp|
      word = Word.create(name: domp[1], sources: [source])
      word.uitdrukking = 2 if domp[2] == "uitdrukking"
      wordtype = Wordtype.find_by_name(domp[2])
      word.wordtypes=[wordtype] if wordtype
      word.countable = 1 if domp[3].downcase == 'ja'
      word.synonym = [domp[4], domp[5]].join('; ') unless domp[4].blank? && domp[5].blank?
      word.description_pap_cw = domp[6..10].join "; "
      word.user_id = this_user.id
      word.save
    end
  end

  def down
    remove_column :words, :uitdrukking
    source = Source.find_by_name('Dòmpereré pa palabra pèrdí i nobo')
    source.words.destroy_all
    source.destroy
  end
end
