class AddMoneyToWords < ActiveRecord::Migration[5.2]
  def up
    add_column :words, :is_money, :integer, default: 1
    add_column :words, :monetary_value_in_mct, :integer, default: 0
    Word.reset_column_information
    Source.create(name: 'Dòmpereré', comment: '© 2017 Lista kompilá pa Delno Tromp (den kuadro di proyekto Dòmpereré); revisá pa Ini Statia i Lucille Berry-Haseth (01-03-2018)')
    source = Source.find_by_name('Dòmpereré')
    wordtype = Wordtype.find_by_name('sustantivo')

    Word.create(name: "Un sèn chikí ", sources: [source], is_money: 2, monetary_value_in_mct: 50)
    Word.create(name: "Tres sèn chikí", sources: [source], is_money: 2, monetary_value_in_mct: 15)
    Word.create(name: "Un plaka grandi ", sources: [source], is_money: 2, monetary_value_in_mct: 25)
    Word.create(name: "Skapadepchi", sources: [source], is_money: 2, monetary_value_in_mct: 50)
    Word.create(name: "Locha", sources: [source], is_money: 2, monetary_value_in_mct: 50)
    Word.create(name: "Zèpelin", sources: [source], is_money: 2, monetary_value_in_mct: 50)
    Word.create(name: "Sepelin", sources: [source], is_money: 2, monetary_value_in_mct: 50)
    Word.create(name: "Stùiver", sources: [source], is_money: 2, monetary_value_in_mct: 50)
    Word.create(name: "Tres plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 75)
    Word.create(name: "Depchi ", sources: [source], is_money: 2, monetary_value_in_mct: 100)
    Word.create(name: "Diestres sèn grandi ", sources: [source], is_money: 2, monetary_value_in_mct: 130)
    Word.create(name: "Shete plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 175)
    Word.create(name: "Nuebe plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 225)
    Word.create(name: "Diesun plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 275)
    Word.create(name: "Dòria un plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 325)
    Word.create(name: "Dòria tres plaka `", sources: [source], is_money: 2, monetary_value_in_mct: 375)
    Word.create(name: "Kuarenta sèn ", sources: [source], is_money: 2, monetary_value_in_mct: 400)
    Word.create(name: "Treria ", sources: [source], is_money: 2, monetary_value_in_mct: 450)
    Word.create(name: "Un yotin", sources: [source], is_money: 2, monetary_value_in_mct: 500)
    Word.create(name: "Un yotin ku dòsplaka ", sources: [source], is_money: 2, monetary_value_in_mct: 550)
    Word.create(name: "Un chilin ", sources: [source], is_money: 2, monetary_value_in_mct: 625)
    Word.create(name: "Kuater ria tres plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 675)
    Word.create(name: "Sinku ria", sources: [source], is_money: 2, monetary_value_in_mct: 750)
    Word.create(name: "Sinku ria sinku plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 875)
    Word.create(name: "Seis ria dòsplaka", sources: [source], is_money: 2, monetary_value_in_mct: 950)
    Word.create(name: "Un heldu ", sources: [source], is_money: 2, monetary_value_in_mct: 1000)
    Word.create(name: "Ocho ria", sources: [source], is_money: 2, monetary_value_in_mct: 1200)
    Word.create(name: "Mei fuèrte ", sources: [source], is_money: 2, monetary_value_in_mct: 1250)
    Word.create(name: "Nuebe ria ", sources: [source], is_money: 2, monetary_value_in_mct: 1350)
    Word.create(name: "Tres yotin sinku plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 1625)
    Word.create(name: "Tres yotin ku dòria ", sources: [source], is_money: 2, monetary_value_in_mct: 1800)
    Word.create(name: "Un patin", sources: [source], is_money: 2, monetary_value_in_mct: 2000)
    Word.create(name: "Un dòlò, un fuèrte", sources: [source], is_money: 2, monetary_value_in_mct: 2500)
    Word.create(name: "Sinku florin ", sources: [source], is_money: 2, monetary_value_in_mct: 5000)
    Word.create(name: "Binti sinku florin ", sources: [source], is_money: 2, monetary_value_in_mct: 25000)
    Word.create(name: "Shen florin ", sources: [source], is_money: 2, monetary_value_in_mct: 100000)
    Word.create(name: "Un sèn grandi ", sources: [source], is_money: 2, monetary_value_in_mct: 10)
    Word.create(name: "Dos sèn grandi ", sources: [source], is_money: 2, monetary_value_in_mct: 20)
    Word.create(name: "Dòsplaka ", sources: [source], is_money: 2, monetary_value_in_mct: 50)
    Word.create(name: "Seis sèn grandi ", sources: [source], is_money: 2, monetary_value_in_mct: 60)
    Word.create(name: "Kuater plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 100)
    Word.create(name: "Sinku plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 125)
    Word.create(name: "Un ria ", sources: [source], is_money: 2, monetary_value_in_mct: 150)
    Word.create(name: "Ocho plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 200)
    Word.create(name: "Dies plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 250)
    Word.create(name: "Dòria", sources: [source], is_money: 2, monetary_value_in_mct: 300)
    Word.create(name: "Dòria dòsplaka", sources: [source], is_money: 2, monetary_value_in_mct: 350)
    Word.create(name: "Dòria kuater plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 400)
    Word.create(name: "Dòria sinku plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 425)
    Word.create(name: "Dòria shete plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 475)
    Word.create(name: "Treria kuater plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 550)
    Word.create(name: "Kuater ria ", sources: [source], is_money: 2, monetary_value_in_mct: 600)
    Word.create(name: "Kuater ria dòsplaka ", sources: [source], is_money: 2, monetary_value_in_mct: 650)
    Word.create(name: "Kuater ria kuater plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 700)
    Word.create(name: "Sinku ria dòsplaka ", sources: [source], is_money: 2, monetary_value_in_mct: 800)
    Word.create(name: "Seis ria ", sources: [source], is_money: 2, monetary_value_in_mct: 900)
    Word.create(name: "Un florin ", sources: [source], is_money: 2, monetary_value_in_mct: 1000)
    Word.create(name: "Sobrekama (1,-  di papel)", sources: [source], is_money: 2, monetary_value_in_mct: 1000)
    Word.create(name: "Un pataka (ocho ria)", sources: [source], is_money: 2, monetary_value_in_mct: 1200)
    Word.create(name: "Ocho ria kuater plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 1300)
    Word.create(name: "Tres yotin ", sources: [source], is_money: 2, monetary_value_in_mct: 1500)
    Word.create(name: "Tres yotin ku dies plaka ", sources: [source], is_money: 2, monetary_value_in_mct: 1750)
    Word.create(name: "Tres yotin ku dòria dòsplaka", sources: [source], is_money: 2, monetary_value_in_mct: 1850)
    Word.create(name: "Un patin ku dòria", sources: [source], is_money: 2, monetary_value_in_mct: 2300)
    Word.create(name: "Dos sinkuenta ", sources: [source], is_money: 2, monetary_value_in_mct: 2500)
    Word.create(name: "Dies florin", sources: [source], is_money: 2, monetary_value_in_mct: 10000)
    Word.create(name: "Sinkuenta florin", sources: [source], is_money: 2, monetary_value_in_mct: 50000)
  end


  def down
    remove_column :words, :is_money
    remove_column :words, :monetary_value_in_mct
  end
end
